//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSmartphoneShoppingStoreEntities : DbContext
    {
        public dbSmartphoneShoppingStoreEntities()
            : base("name=dbSmartphoneShoppingStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Cart> Table_Cart { get; set; }
        public virtual DbSet<Table_CartStatus> Table_CartStatus { get; set; }
        public virtual DbSet<Table_Category> Table_Category { get; set; }
        public virtual DbSet<Table_MemberRole> Table_MemberRole { get; set; }
        public virtual DbSet<Table_Members> Table_Members { get; set; }
        public virtual DbSet<Table_Roles> Table_Roles { get; set; }
        public virtual DbSet<Table_ShippingDetails> Table_ShippingDetails { get; set; }
        public virtual DbSet<Table_SlideImage> Table_SlideImage { get; set; }
        public virtual DbSet<Table_Product> Table_Product { get; set; }
        public virtual DbSet<SiteUser> SiteUser { get; set; }
    }
}
